### ISSUE TITLE
Missing operand after "-u"

### ISSUE THREAD

**Issue by KOMA-Elektronik** [madworm/KiCad-Stuff#1]
Hello madworm,

I tried your tool and it works well for me when using it in the command line. But when I try to launch it via "git difftool" it tells me that there is nothing specified after "-u" which I gather should be the two files to compare. I tried both
- git difftool -t visdiff [xxx] [yyy]
- git difftool [xxx] [yyy]

All my variables are set correctly I think. These are my relevant outputs of git config --list:
diff.tool=visdiff
diff.guitool=visdiff
merge.tool=visdiff
difftool.visdiff.path=/home/me/opt/visdiff/scripts/visual-diffs_on_gerber-files/
difftool.visdiff.cmd=vis_diff.sh
mergetool.visdiff.path=/home/me/opt/visdiff/scripts/visual-diffs_on_gerber-files/
mergetool.visdiff.cmd=vis_diff.sh

Do you have any idea what could go wrong? Thanks a lot for your time!!

**Comment by madworm** [comment]
Yes, that error message was thrown when no CLI parameters were supplied. I've added a more suitable error message now.

difftool.visdiff.cmd should be set to 'vis_diff.sh $LOCAL $REMOTE'

or in your .gitconfig:

[difftool "visdiff"]
        path = /usr/local/bin/
        cmd = vis_diff.sh $LOCAL $REMOTE

**Comment by madworm** [comment]
> When git difftool is invoked with this tool (either through the -t or --tool option or the diff.tool configuration variable) the configured command line will be invoked with the following variables available: $LOCAL is set to the name of the temporary file containing the contents of the diff pre-image and $REMOTE is set to the name of the temporary file containing the contents of the diff post-image. $MERGED is the name of the file which is being compared.  $BASE is provided for compatibility with custom merge tool commands and has the same value as $MERGED.

**Comment by KOMA-Elektronik** [comment]
Hey @madworm that is so sweet of you to answer so fast. Now it works perfectly! This is a great tool, thanks for sharing it!
